<?php
// auth-generated by DefineConfigHandler
// date: 01/20/2015 10:56:32
if (!defined('MO_DEFAULT_MODULE')) { define('MO_DEFAULT_MODULE', 'Default'); }
if (!defined('MO_DEFAULT_ACTION')) { define('MO_DEFAULT_ACTION', 'Index'); }
if (!defined('MO_ERROR_404_MODULE')) { define('MO_ERROR_404_MODULE', 'Default'); }
if (!defined('MO_ERROR_404_ACTION')) { define('MO_ERROR_404_ACTION', 'Error404'); }
if (!defined('MO_LOGIN_MODULE')) { define('MO_LOGIN_MODULE', 'Default'); }
if (!defined('MO_LOGIN_ACTION')) { define('MO_LOGIN_ACTION', 'Login'); }
if (!defined('MO_MODULE_DISABLED_MODULE')) { define('MO_MODULE_DISABLED_MODULE', 'Default'); }
if (!defined('MO_MODULE_DISABLED_ACTION')) { define('MO_MODULE_DISABLED_ACTION', 'ModuleDisabled'); }
if (!defined('MO_SECURE_MODULE')) { define('MO_SECURE_MODULE', 'Default'); }
if (!defined('MO_SECURE_ACTION')) { define('MO_SECURE_ACTION', 'Secure'); }
if (!defined('MO_UNAVAILABLE_MODULE')) { define('MO_UNAVAILABLE_MODULE', 'Default'); }
if (!defined('MO_UNAVAILABLE_ACTION')) { define('MO_UNAVAILABLE_ACTION', 'Unavailable'); }
if (!defined('MO_AVAILABLE')) { define('MO_AVAILABLE', true); }
if (!defined('MO_ACTION_ACCESSOR')) { define('MO_ACTION_ACCESSOR', 'action'); }
if (!defined('MO_MODULE_ACCESSOR')) { define('MO_MODULE_ACCESSOR', 'module'); }
if (!defined('MO_CONTENT_TYPE')) { define('MO_CONTENT_TYPE', 'html'); }
if (!defined('MO_MOD_PUB')) { define('MO_MOD_PUB', '/modpub'); }
if (!defined('MO_PATH_INFO_ARRAY')) { define('MO_PATH_INFO_ARRAY', 'SERVER'); }
if (!defined('MO_PATH_INFO_KEY')) { define('MO_PATH_INFO_KEY', 'PATH_INFO'); }
if (!defined('MO_URL_FORMAT')) { define('MO_URL_FORMAT', 'GET'); }
if (!defined('MO_USE_DATABASE')) { define('MO_USE_DATABASE', true); }
if (!defined('MO_USE_SECURITY')) { define('MO_USE_SECURITY', true); }
if (!defined('MO_USER_NAMESPACE')) { define('MO_USER_NAMESPACE', 'org/mojavi'); }
if (!defined('MO_CACHE_USER')) { define('MO_CACHE_USER', 'apache'); }
if (!defined('MO_CACHE_GROUP')) { define('MO_CACHE_GROUP', 'apache'); }
if (!defined('MO_LOG_FOLDER')) { define('MO_LOG_FOLDER', '/var/log/adl'); }
if (!defined('MO_VERSION_FILE')) { define('MO_VERSION_FILE', '/home/adl/webapp/meta/version'); }
?>