<?php
// auth-generated by FilterConfigHandler
// date: 01/20/2015 10:56:42

$filters = array();
$filter = new \Mojavi\Filter\ExecutionTimeFilter();
$filter->initialize($this->context, array('comment' => true));
$filters[] = $filter;
$list[$moduleName] =& $filters;
?>