<?php
// auth-generated by RootConfigHandler
// date: 01/20/2015 10:56:32

self::$handlers['config/autoload.ini'] = new \Mojavi\Config\AutoloadConfigHandler();
self::$handlers['config/databases.ini'] = new \Mojavi\Config\DatabaseConfigHandler();
self::$handlers['config/settings.ini'] = new \Mojavi\Config\DefineConfigHandler();
self::$handlers['config/settings.ini']->initialize(array('prefix' => 'MO_'));
self::$handlers['factories.ini'] = new \Mojavi\Config\FactoryConfigHandler();
self::$handlers['compile.conf'] = new \Mojavi\Config\CompileConfigHandler();
self::$handlers['filters.ini'] = new \Mojavi\Config\FilterConfigHandler();
self::$handlers['logging.ini'] = new \Mojavi\Config\LoggingConfigHandler();
self::$handlers['modules/*/config/module.ini'] = new \Mojavi\Config\ModuleConfigHandler();
self::$handlers['modules/*/validate/*.ini'] = new \Mojavi\Config\ValidatorConfigHandler();
self::$handlers['modules/*/config/*_db.ini'] = new \Mojavi\Config\DBInterfaceConfigHandler();
self::$handlers['lib/dao/*/config/*_db.ini'] = new \Mojavi\Config\DBInterfaceConfigHandler();
?>