<?php
// auth-generated by ModuleConfigHandler
// date: 01/20/2015 10:56:42
define('MOD_DEFAULT_ENABLED', true);
define('MOD_DEFAULT_VERSION', 0.1);
define('MOD_DEFAULT_NAME', 'Default');
define('MOD_DEFAULT_DESCRIPTION', 'A Default module');
?>